from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_font('Helvetica', 'B', 24)
pdf.cell(0, 12, 'IS Lab 6', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.set_font('Helvetica', 'B', 14)
pdf.cell(0, 8, 'Genetic Algorithm for 0/1 Knapsack', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.set_font('Helvetica', '', 10)
pdf.cell(0, 7, 'IT24610796', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.ln(4)
pdf.set_font('Helvetica', 'B', 11)
pdf.cell(0, 7, 'Problem', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 5, 'Given n items with weights w[i] and profits p[i], select a subset maximizing total profit with total weight <= capacity C. NP-hard; solved optimally via DP for small instances.')
pdf.ln(3)
pdf.set_font('Helvetica', 'B', 11)
pdf.cell(0, 7, 'Instance', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 10)
pdf.cell(0, 5, 'Dataset: OR-Library P07 (15 items, capacity 750)', new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 5, 'n=15, C=750', new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 5, 'Optimal (DP): 1458', new_x="LMARGIN", new_y="NEXT")
pdf.ln(3)
pdf.set_font('Helvetica', 'B', 11)
pdf.cell(0, 7, 'GA Design', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 5, 'Binary encoding: 1 = take item. Fitness: hard penalty = profit - 1000*max(0, weight-capacity). Selection: tournament k=3. Crossover: 2-point (pc=0.9). Mutation: bit-flip (pm=0.02). Elitism: 2. Pop: 150, Gens: 200. Seed: 42.')
pdf.ln(3)
pdf.set_font('Helvetica', 'B', 11)
pdf.cell(0, 7, 'Results', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 10)
pdf.cell(0, 5, 'Baseline (k=3, 2pt, pm=0.02): optimal=1458, GA=1444, gap=0.96%.', new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 5, 'Tournament k=2: 1442 (99.8% of baseline) - less pressure, worse.', new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 5, 'Tournament k=4: 1450 (100.4% of baseline) - best variant.', new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 5, 'Roulette: infeasible due to negative fitness values in DEAP.', new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 5, 'Roulette+Shift: 1442 (99.8%). Rank: 1440 (99.7%).', new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 5, '1-point crossover: 1440 (99.7%). 2-point: 1444 (100%).', new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 5, 'Uniform crossover: 1436 (99.4%) - too much disruption.', new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 5, 'pm=0.01: 1440 (99.7%). pm=0.02: 1444 (100%). pm=0.10: 1428 (99.0%).', new_x="LMARGIN", new_y="NEXT")
pdf.ln(3)
pdf.set_font('Helvetica', 'B', 11)
pdf.cell(0, 7, 'Convergence', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 5, 'Best fitness rises from 500 to 1444 over 200 generations. Average rises from 400 to 1188. Gap between best and avg widens over time (selection pressure). Plateau reached around gen 100-120.')
pdf.ln(3)
pdf.set_font('Helvetica', 'B', 11)
pdf.cell(0, 7, 'Conclusion', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 5, 'GA achieves 99% of optimal for this medium instance. Tournament k=4 gives best results due to higher selection pressure on a small population. 2-point crossover preserves building blocks better than uniform. pm=0.02 balances exploration vs exploitation. Convergence plateaus as population converges.')
pdf.ln(3)
pdf.set_font('Helvetica', 'B', 11)
pdf.cell(0, 7, 'Code Repository', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', 'B', 10)
pdf.set_text_color(0, 0, 255)
pdf.cell(0, 6, 'https://github.com/IT24610796/lab', new_x="LMARGIN", new_y="NEXT")
pdf.set_text_color(0, 0, 0)
pdf.ln(3)
pdf.set_font('Helvetica', '', 9)
pdf.multi_cell(0, 5, 'Dependencies: Python 3.11, DEAP, matplotlib. Run: python ga_knapsack.py (from project root). Virtual env: .venv/ with packages in requirements.txt.')
pdf.output('lab6_report.pdf')
print('PDF created: lab6_report.pdf')
